// Generated by CoffeeScript 1.4.0
var Polygon, Vertex;

Vertex = (function() {

  Vertex.list = function(vertices) {
    var v, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = vertices.length; _i < _len; _i++) {
      v = vertices[_i];
      _results.push((function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args);
        return Object(result) === result ? result : child;
      })(Vertex, v, function(){}));
    }
    return _results;
  };

  function Vertex(x, y) {
    this.x = x;
    this.y = y;
  }

  return Vertex;

})();

Polygon = (function() {

  function Polygon(vertices) {
    this.vertices = vertices;
  }

  Polygon.prototype.draw = function(context) {
    var v, _i, _len, _ref;
    context.beginPath();
    context.strokeStyle = "#00b";
    v = this.vertices[this.vertices.length - 1];
    context.moveTo(v.x, v.y);
    _ref = this.vertices;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      v = _ref[_i];
      context.lineTo(v.x, v.y);
    }
    return context.stroke();
  };

  return Polygon;

})();

$(document).ready(function() {
  var canvas, context, triangle;
  canvas = $("canvas")[0];
  context = canvas.getContext("2d");
  triangle = new Polygon(Vertex.list([[10, 10], [100, 60], [25, 100]]));
  return triangle.draw(context);
});
